export { default as ProductOverview } from './Overview'
export { default as ProductMedicines } from './Medicines'
export { default as VitaminFeature } from './VitaminFeature'
export { default as ProductFaq } from './Faq'
export { default as ProductReviews } from './Reviews'
export { default as ProductFeature } from './Feature'
export { default as ProductCard } from './Card'
